### ISSUE TITLE
讨论区！

### ISSUE THREAD

**Issue by zhu-ty** [zhu-ty/DA32ProtocolJava#1]
童鞋们好~组内项目启动后我会不定期看看大家的代码并帮助大家修改，这个地方可以作为一个很不错的留言讨论区！
（这也是我第一次试验此功能2333）
麻烦看到此消息的在这下边回复下吧~ 我故意不在群内说看看谁能看到~

**Comment by LPMzhuo** [comment]
收到~辛苦啦萌娃！

发自我的 iPhone

**Comment by niujiahe** [comment]
哈哈哈

**Comment by HandsomeFeng** [comment]
666

在2015-11-21 00:11:37，冯乔俊fqj13@mails.tsinghua.edu.cn写道：

童鞋们好~组内项目启动后我会不定期看看大家的代码并帮助大家修改，这个地方可以作为一个很不错的留言讨论区！
（这也是我第一次试验此功能2333）
麻烦看到此消息的在这下边回复下吧~ 我故意不在群内说看看谁能看到~
